### ISSUE TITLE
Multiple Logcat Errors (Kimob=Master, Api 33, Ver=com.google.firebase:firebase-ads:21.4.0)

### ISSUE THREAD

**Issue by boyintheroom** [MichaelStott/KivMob#127]
```
logcat
02-07 13:45:58.752 29198 29198 I python  :  Traceback (most recent call last):
02-07 13:45:58.756 29198 29198 I python  :    File "/home/dheeraj/buildozer/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/Phenon/armeabi-v7a/android/runnable.py", line 38, in run
02-07 13:45:58.756 29198 29198 I python  :    File "/home/dheeraj/buildozer/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/Phenon/armeabi-v7a/kivmob.py", line 231, in __init__
02-07 13:45:58.756 29198 29198 I python  :  NameError: name 'MobileAds' is not defined
02-07 13:45:58.760 29198 29198 I python  :  Traceback (most recent call last):
02-07 13:45:58.760 29198 29198 I python  :    File "/home/dheeraj/buildozer/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/Phenon/armeabi-v7a/android/runnable.py", line 38, in run
02-07 13:45:58.760 29198 29198 I python  :    File "/home/dheeraj/buildozer/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/Phenon/armeabi-v7a/kivmob.py", line 303, in load_rewarded_ad
02-07 13:45:58.760 29198 29198 I python  :    File "/home/dheeraj/buildozer/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/Phenon/armeabi-v7a/kivmob.py", line 334, in _get_builder
02-07 13:45:58.767 29198 29198 I python  :  AttributeError: 'AndroidBridge' object has no attribute '_test_devices'
02-07 13:45:58.775 29198 29198 I python  :  Traceback (most recent call last):
02-07 13:45:58.776 29198 29198 I python  :    File "/home/dheeraj/buildozer/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/Phenon/armeabi-v7a/android/runnable.py", line 38, in run
02-07 13:45:58.776 29198 29198 I python  :    File "/home/dheeraj/buildozer/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/Phenon/armeabi-v7a/kivmob.py", line 298, in set_rewarded_ad_listener
02-07 13:45:58.776 29198 29198 I python  :  NameError: name 'AdMobRewardedVideoAdListener' is not defined
```
Having this error for 8 days couldnt figure it out. @MichaelStott Sir Please help.

Api=33
Kivy=master(2.2.0)
Kivymd=1.2.0.dev0
Kivmob=master
Ads version=com.google.firebase:firebase-ads:21.4.0
jdk=17
python 3.8

**Comment by boyintheroom** [comment]
@nekoprog @MichaelStott Problem Persists. No Change In The Error. 😣

**Comment by nekoprog** [comment]
@boyintheroom you can try pull from my patch branch, or wait for @MichaelStott to merge my PR

**Comment by boyintheroom** [comment]
@nekoprog The updated code says "TODO since no more RewardedVideoAd"
does that mean there will be no rewarded ads support further in future?
I have Only Integrated rewarded video ads with kivmob.

**Comment by nekoprog** [comment]
There is rewarded video ads, but you have to implement it yourself since those class name is not there in latest admob-ads, maybe google change the class name. Hence, a TODO for others who can help implement newer code.

**Comment by boyintheroom** [comment]
How Can I pull from your patch branch (im new)?
& if i do will it fix the error?

**Comment by nekoprog** [comment]
It will fix NameError *** is not defined. That's all I can do right now.

**Comment by boyintheroom** [comment]
That Would Be Great
@nekoprog, can @MichaelStott edit kivmob.py to latest google admob class names

**Comment by boyintheroom** [comment]
@nekoprog hi, can i use rewarded interstitial in place of rewarded video ads?
