### ISSUE TITLE
I can't add KivMob

### ISSUE THREAD

**Issue by DarVater** [MichaelStott/KivMob#129]
Sorry for stealing your time, but I don't understand what I'm doing wrong.
I can't show the test banner

Python 3.8.10
kivy 2.1.0
jnius 1.1.0

Операционная система: KDE neon 5.26
Версия KDE Plasma: 5.26.0
Версия KDE Frameworks: 5.99.0
Версия Qt: 5.15.7
Версия ядра: 5.15.0-60-generic (64-бита)
Графическая платформа: X11
Процессоры: 4 × AMD Ryzen 3 1300X Quad-Core Processor
Память: 7,7 GiB ОЗУ
Графический процессор: NVIDIA GeForce GTX 1050/PCIe/SSE2
Производитель: BIOSTAR Group
Название продукта: B350GTN

self.ads.show_banner() I already tried to call it with a delay and from another screen, so the time to load was

```
from kivmob import KivMob, TestIds

class MyApp(App):
    def build(self): 
        self.ads = KivMob(TestIds.APP)
        self.ads.new_banner(TestIds.BANNER)
        self.ads.request_banner()
        self.ads.show_banner() 
        return screen_manager

if __name__ == '__main__':
    MyApp().run()
```

buildozer.spec
requirements = python3, kivy, android, jnius, https://github.com/nekoprog/KivMob/archive/refs/heads/master.zip
android.permissions = INTERNET, ACCESS_NETWORK_STATE
android.api = 33
android.minapi = 21
android.sdk = 33
android.ndk = 25b
android.gradle_dependencies = com.google.firebase:firebase-ads:21.4.0
android.meta_data = com.google.android.gms.ads.APPLICATION_ID=ca-app-pub-3940256099942544~3347511713
p4a.branch = master

02-17 00:06:14.042 16345 16651 I python  : Android kivy bootstrap done. __name__ is __main__
02-17 00:06:14.043 16345 16651 I python  : AND: Ran string
02-17 00:06:14.043 16345 16651 I python  : Run user program, change dir and execute entrypoint
02-17 00:06:14.189 16345 16651 I python  : [WARNING] [Config      ] Older configuration version detected (0 instead of 24)
02-17 00:06:14.190 16345 16651 I python  : [WARNING] [Config      ] Upgrading configuration in progress.
02-17 00:06:14.194 16345 16651 I python  : [INFO   ] [Logger      ] Record log in /data/user/0/org.test.like_robo/files/app/.kivy/logs/kivy_23-02-17_0.txt
02-17 00:06:14.194 16345 16651 I python  : [INFO   ] [Kivy        ] v2.1.0
02-17 00:06:14.194 16345 16651 I python  : [INFO   ] [Kivy        ] Installed at "/data/user/0/org.test.like_robo/files/app/_python_bundle/site-packages/kivy/__init__.pyc"
02-17 00:06:14.195 16345 16651 I python  : [INFO   ] [Python      ] v3.9.9 (main, Feb  8 2023, 19:10:42) 
02-17 00:06:14.195 16345 16651 I python  : [Clang 14.0.6 (https://android.googlesource.com/toolchain/llvm-project 4c603efb
02-17 00:06:14.195 16345 16651 I python  : [INFO   ] [Python      ] Interpreter at ""
02-17 00:06:14.195 16345 16651 I python  : [INFO   ] [Logger      ] Purge log fired. Processing...
02-17 00:06:14.196 16345 16651 I python  : [INFO   ] [Logger      ] Purge finished!
02-17 00:06:14.199 16345 16651 I python  : [INFO   ] [Factory     ] 189 symbols loaded
02-17 00:06:15.350 16345 16651 I python  : [INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2 (img_pil, img_ffpyplayer ignored)
02-17 00:06:15.392 16345 16651 I python  : [INFO   ] [Text        ] Provider: sdl2
02-17 00:06:15.824 16345 16651 I python  : [ERROR  ] [KivMob      ] Cannot load AdMob classes. Check buildozer.spec.
02-17 00:06:15.878 16345 16651 I python  : [INFO   ] [Window      ] Provider: sdl2
02-17 00:06:15.913 16345 16651 I python  : [INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
02-17 00:06:15.919 16345 16651 I python  : [INFO   ] [GL          ] Backend used <sdl2>
02-17 00:06:15.920 16345 16651 I python  : [INFO   ] [GL          ] OpenGL version <b'OpenGL ES 3.2 V@415.0 (GIT@389f9e1, I4b4012dc33, 1605186217) (Date:11/12/20)'>
02-17 00:06:15.920 16345 16651 I python  : [INFO   ] [GL          ] OpenGL vendor <b'Qualcomm'>
02-17 00:06:15.921 16345 16651 I python  : [INFO   ] [GL          ] OpenGL renderer <b'Adreno (TM) 512'>
02-17 00:06:15.921 16345 16651 I python  : [INFO   ] [GL          ] OpenGL parsed version: 3, 2
02-17 00:06:15.922 16345 16651 I python  : [INFO   ] [GL          ] Texture max size <16384>
02-17 00:06:15.923 16345 16651 I python  : [INFO   ] [GL          ] Texture max units <16>
02-17 00:06:16.011 16345 16651 I python  : [INFO   ] [Window      ] auto add sdl2 input provider
02-17 00:06:16.012 16345 16651 I python  : [INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
02-17 00:06:16.024 16345 16651 I python  : [WARNING] [Factory     ] Ignored class "BackButton" re-declaration. Current -  module: None, cls: <class 'sistem.BackButton'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: Button, filename: None.
02-17 00:06:16.025 16345 16651 I python  : [WARNING] [Factory     ] Ignored class "StartButton" re-declaration. Current -  module: None, cls: <class 'sistem.StartButton'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: Button, filename: None.
02-17 00:06:16.147 16345 16651 I python  : [INFO   ] [GL          ] NPOT texture support is available
02-17 00:06:16.447 16345 16651 I python  : [INFO   ] [KivMob      ] __init__ called.
02-17 00:06:16.447 16345 16651 I python  : [INFO   ] [KivMob      ] Android platform detected.
02-17 00:06:16.450 16345 16651 I python  : [INFO   ] [KivMob      ] new_banner() called.
02-17 00:06:16.452 16345 16345 I python  :  Traceback (most recent call last):
02-17 00:06:16.452 16345 16651 I python  : [INFO   ] [KivMob      ] request_banner() called.
02-17 00:06:16.454 16345 16345 I python  :    File "/home/bilcko/ads_test/kivmob-quickstart/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/like_robo/arm64-v8a/android/runnable.py", line 38, in run
02-17 00:06:16.454 16345 16651 I python  : [INFO   ] [KivMob      ] show_banner() called.
02-17 00:06:16.456 16345 16345 I python  :    File "/home/bilcko/ads_test/kivmob-quickstart/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/like_robo/arm64-v8a/kivmob.py", line 188, in __init__
02-17 00:06:16.456 16345 16345 I python  :  NameError: name 'MobileAds' is not defined
02-17 00:06:16.478 16345 16651 I python  : [WARNING] [Base        ] Unknown <android> provider
02-17 00:06:16.478 16345 16345 I python  :  Traceback (most recent call last):
02-17 00:06:16.479 16345 16651 I python  : [INFO   ] [Base        ] Start application main loop
02-17 00:06:16.495 16345 16345 I python  :    File "/home/bilcko/ads_test/kivmob-quickstart/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/like_robo/arm64-v8a/android/runnable.py", line 38, in run
02-17 00:06:16.495 16345 16345 I python  :    File "/home/bilcko/ads_test/kivmob-quickstart/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/like_robo/arm64-v8a/kivmob.py", line 204, in new_banner
02-17 00:06:16.498 16345 16345 I python  :  NameError: name 'View' is not defined
02-17 00:06:16.511 16345 16345 I python  :  Traceback (most recent call last):
02-17 00:06:16.511 16345 16345 I python  :    File "/home/bilcko/ads_test/kivmob-quickstart/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/like_robo/arm64-v8a/android/runnable.py", line 38, in run
02-17 00:06:16.511 16345 16345 I python  :    File "/home/bilcko/ads_test/kivmob-quickstart/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/like_robo/arm64-v8a/kivmob.py", line 221, in request_banner
02-17 00:06:16.511 16345 16345 I python  :    File "/home/bilcko/ads_test/kivmob-quickstart/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/like_robo/arm64-v8a/kivmob.py", line 290, in _get_builder
02-17 00:06:16.517 16345 16345 I python  :  AttributeError: 'AndroidBridge' object has no attribute '_test_devices'
02-17 00:06:16.544 16345 16345 I python  :  Traceback (most recent call last):
02-17 00:06:16.545 16345 16345 I python  :    File "/home/bilcko/ads_test/kivmob-quickstart/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/like_robo/arm64-v8a/android/runnable.py", line 38, in run
02-17 00:06:16.545 16345 16345 I python  :    File "/home/bilcko/ads_test/kivmob-quickstart/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/like_robo/arm64-v8a/kivmob.py", line 225, in show_banner
02-17 00:06:16.546 16345 16345 I python  :  NameError: name 'View' is not defined

**Comment by DarVater** [comment]
I managed to see a test banner with buildozer :
android.gradle_dependencies = com.google.firebase:firebase-ads:15.0.0
android.api = 31
android.minapi = 21
android.sdk = 24
android.ndk = 25b
p4a.branch = master
android.meta_data = com.google.android.gms.ads.APPLICATION_ID=ca-app-pub-3940256099942544~3347511713
requirements = python3, kivy, android, jnius, https://github.com/MichaelStott/KivMob/archive/refs/heads/master.zip

**Comment by Mglt-b** [comment]
Hello, did you find an issue please ?

**Comment by MichaelStott** [comment]
Not able to replicate this, but likely fixed with the latest updates. Please reopen if you encounter any additional issues.
