### ISSUE TITLE
AttributeError: 'AndroidBridge' object has no attribute '_test_devices'

### ISSUE THREAD

**Issue by vimisms** [MichaelStott/KivMob#137]
Configured buildozer.spec as mentioned in the below:

https://github.com/MichaelStott/KivMob

but getting this when I try to show a simple banner ad:

07-12 18:19:06.466  5839  5839 I python  :  Traceback (most recent call last):
07-12 18:19:06.466  5839  5839 I python  :    File "/home/vimis/color/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/colormatch/arm64-v8a/android/runnable.py", line 38, in run
07-12 18:19:06.466  5839  5839 I python  :    File "/home/vimis/color/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/colormatch/arm64-v8a/kivmob.py", line 221, in __init__
07-12 18:19:06.466  5839  5839 I python  :    File "jnius/jnius_export_class.pxi", line 1150, in jnius.jnius.JavaMultipleMethod.__call__
07-12 18:19:06.466  5839  5839 I python  :  jnius.jnius.JavaException: No static methods called initialize in com/google/android/gms/ads/MobileAds matching your arguments, requested: (<org.kivy.android.PythonActivity at 0x735cb3a520 jclass=org/kivy/android/PythonActivity jself=<LocalRef obj=0xd12a at 0x735d20bf90>>, 'ca-app-pub-3940256099942544~3347511713'), available: ['(Landroid/content/Context;)V', '(Landroid/content/Context;Lcom/google/android/gms/ads/initialization/OnInitializationCompleteListener;)V']
07-12 18:19:06.466  5839  5883 I python  : [INFO   ] [KivMob      ] new_banner() called.
07-12 18:19:06.472  5839  5883 I python  : [INFO   ] [KivMob      ] request_banner() called.
07-12 18:19:06.473  5839  5883 I python  : [INFO   ] [KivMob      ] show_banner() called.
07-12 18:19:06.485  5839  5839 I python  :  Traceback (most recent call last):
07-12 18:19:06.485  5839  5839 I python  :    File "/home/vimis/color/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/colormatch/arm64-v8a/android/runnable.py", line 38, in run
07-12 18:19:06.485  5839  5839 I python  :    File "/home/vimis/color/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/colormatch/arm64-v8a/kivmob.py", line 259, in request_banner
07-12 18:19:06.486  5839  5839 I python  :    File "/home/vimis/color/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/build/python-installs/colormatch/arm64-v8a/kivmob.py", line 329, in _get_builder
07-12 18:19:06.486  5839  5839 I python  :  AttributeError: 'AndroidBridge' object has no attribute '_test_devices'
07-12 18:19:06.516  5839  5883 I python  : [INFO   ] [GL          ] NPOT texture support is available
07-12 18:19:06.550  5839  5883 I python  : [WARNING] [Base        ] Unknown <android> provider
07-12 18:19:06.550  5839  5883 I python  : [INFO   ] [Base        ] Start application main loop

**Comment by callumpurcell1** [comment]
Also getting this error
