### ISSUE TITLE
Banner ad error

### ISSUE THREAD

**Issue by yunus-ceyhan** [MichaelStott/KivMob#26]
Hey Michael, at first thank you so much for making kivmob work again for the new api.
But it seems that banner ad not working anymore. i have test both interstitial and banner ads, interstitial ad working well but banner ad wasn't showed up. i have checked log file it prints some errors below.

```
[WARNING] stderr: File "/data/data/com.ceyhan.sets/files/app/kivmob.py", line 177, in request_banner [WARNING] stderr: self._adview.loadAd(AdRequestBuilder().build()) [WARNING] stderr: File "jnius/jnius_export_class.pxi", line 734, in jnius.jnius.JavaMethod.__call__ (jnius/jnius.c:23930) [WARNING] stderr: File "jnius/jnius_export_class.pxi", line 828, in jnius.jnius.JavaMethod.call_method (jnius/jnius.c:25014) [WARNING] stderr: File "jnius/jnius_utils.pxi", line 93, in jnius.jnius.check_exception (jnius/jnius.c:3882) [WARNING] stderr: JavaException: JVM exception occurred: The ad size and ad unit ID must be set before loadAd is called.
```

**Comment by MichaelStott** [comment]
Can you post your banner ad code here?

**Comment by yunus-ceyhan** [comment]
@MichaelStott 

    def on_start(self):
        self.ban = KivMob("ca-app-pub-9581969215819839~979.....")
        self.ban.add_test_device("31D0182E........")
        self.ban.new_banner({"unitID":"ca-app-pub-9581969215819839/241....."})
        self.ban.request_banner()
        Clock.schedule_once(self.show_ban,1)

    def show_ban(self,*args):
        self.ban.show_banner()

**Comment by MichaelStott** [comment]
the new_banner function was updated in 2.0. Try this:

`self.new_banner(self, "ca-app-pub-9581969215819839/241.....",)`

**Comment by yunus-ceyhan** [comment]
@MichaelStott i did but still no luck..


```
WARNING] stderr: Traceback (most recent call last): [WARNING] stderr: File "/data/user/0/com.ceyhan.sets/files/app/_python_bundle/site-packages/android/runnable.py", line 35, in run [WARNING] stderr: self.func(*self.args, **self.kwargs) [WARNING] stderr: File "/data/user/0/com.ceyhan.sets/files/app/_python_bundle/site-packages/kivmob.py", line 196, in new_banner [WARNING] stderr: self._adview.setAdUnitId(unitID) [WARNING] stderr: File "jnius/jnius_export_class.pxi", line 728, in jnius.jnius.JavaMethod.__call__ (jnius/jnius.c:23882) [WARNING] stderr: File "jnius/jnius_conversion.pxi", line 87, in jnius.jnius.populate_args (jnius/jnius.c:7473) [WARNING] stderr: JavaException: Invalid python object for this argument. Want u'java/lang/String', got set(['ca-app-pub-9581969215819839/2419311601']) [WARNING] stderr: Traceback (most recent call last): [WARNING] stderr: File "/data/user/0/com.ceyhan.sets/files/app/_python_bundle/site-packages/android/runnable.py", line 35, in run [WARNING] stderr: self.func(*self.args, **self.kwargs) [WARNING] stderr: File "/data/user/0/com.ceyhan.sets/files/app/_python_bundle/site-packages/kivmob.py", line 211, in request_banner [WARNING] stderr: self._adview.loadAd(self._get_builder(options).build()) [WARNING] stderr: File "jnius/jnius_export_class.pxi", line 734, in jnius.jnius.JavaMethod.__call__ (jnius/jnius.c:23930) [WARNING] stderr: File "jnius/jnius_export_class.pxi", line 828, in jnius.jnius.JavaMethod.call_method (jnius/jnius.c:25014) [WARNING] stderr: File "jnius/jnius_utils.pxi", line 93, in jnius.jnius.check_exception (jnius/jnius.c:3882) [WARNING] stderr: JavaException: JVM exception occurred: The ad size and ad unit ID must be set before loadAd is called. [INFO ] KivMob: Android platform detected. [INFO ] KivMob: Android platform detected. [INFO ] Base: Leaving application in progress... [ERROR ] Base: No event listeners have been created [ERROR ] Base: Application will leave
```
