### ISSUE TITLE
 Problem with PythonActivity$AdCmd

### ISSUE THREAD

**Issue by IvanDragogear** [MichaelStott/KivMob#7]
Hello, I tried to use the kivmob, but when debugging I get the following error:

```
I/python  (32524): [GCC 4.8]
I/python  (32524):  Traceback (most recent call last):
I/python  (32524):    File "/home/myspace/Desktop/topsecret/.buildozer/android/app/main.py", line 1, in <module>
I/python  (32524):    File "/home/myspace/Desktop/topsecret/.buildozer/android/app/kivmob.py", line 8, in <module>
I/python  (32524):    File "/home/myspace/Desktop/topsecret/.buildozer/android/platform/build/dists/myapp/private/lib/python2.7/site-packages/jnius/reflect.py", line 159, in autoclass
I/python  (32524):    File "jnius/jnius_export_func.pxi", line 26, in jnius.jnius.find_javaclass
I/python  (32524):  jnius.jnius.JavaException: Class not found 'org/kivy/android/PythonActivity$AdCmd'
I/python  (32524): Python for android ended.
```

I'm using Buildozer 0.35dev
When I add a new requirement first I have to create the package with p4a.bootstrap = sdl2
then I build the apk with p4a.bootstrap = sdl2-admob
otherwise it shows me this error:
ImportError: No module named sdl2-admob

**Comment by IvanDragogear** [comment]
The error was because I omitted a few steps:

-To clone python-for-android-admob:
$ git clone https://github.com/MichaelStott/python-for-android-admob.git

-And set python-for-android directory in buildozer.spec:
p4a.source_dir = ~/python-for-android-admob
